<?php
declare (strict_types=1);

namespace app\shop\controller;

use think\facade\Db;
use think\facade\View;

class Banner extends Common
{

    public static $table = "do_banner";

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        $data = Db::table(self::$table)->where('shop_id',$this->shop['id'])->order("sort desc,id desc")->select();

        return view("", ["lists" => $data]);
    }

    public function add()
    {

        if (request()->isPost()) {
            $post = input("post.");
            $post["shop_id"] = $this->shop['id'];
            if ($post["id"]) {

                Db::table(self::$table)
                    ->update($post);
            } else {
                Db::table(self::$table)
                    ->insert($post);
            }
            $return = [
                "code" => 0,
                "msg" => "操作成功",
                "url" => (string)url("index")
            ];

            return json($return);
        } else {

            $id = input("get.id", 0, "intval");
            if ($id > 0) {
                $data = Db::table(self::$table)->find($id);
                View::assign($data);
            }
            return view();
        }
    }

    public function sort()
    {
        $data = input("post.");
        foreach ($data["sort"] as $id => $sort) {
            $update = ["id" => $id,
                "sort" => $sort
            ];
            Db::table(self::$table)
                ->update($update);
        }
        $return = [
            "code" => 0,
            "msg" => "排序成功",
            "url" => (string)url("index")
        ];

        return json($return);
    }

    public function delete()
    {
        $id = input("get.id");
        Db::table(self::$table)->delete($id);
        $return = ["code" => 0, "msg" => "操作成功", "url" => (string)url("index")];
        return json($return);
    }
}
