<?php
declare (strict_types=1);

namespace app\shop\controller;

use think\facade\Db;
use think\facade\View;
use app\common\controller\LianKePrinter;
use app\model\CartModel;
use think\facade\Log;

class Refund extends Common
{
    const TABLE = "do_order";

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $type = input("type");
        $id = input("param.id", 0, "intval");
        if ($type == 2) {
            $inserttime = Db::table('do_order')->where('id', $id)->value('inserttime');
            if ($inserttime > time() - 86400) {
                return $this->toYesRefund($id, 'index');
            } else {
                return $this->toNoRefund($id, 2, 'index', true);
            }
        } else if ($type == 3) {
            return $this->toNoRefund($id, 2, 'index');
        } else if ($type == 4) {
            return $this->toNoRefund($id, 6, 'index');
        }

        $where = [];
        //print_r($this->shop["id"]);
        $where[] = ["a.shop_id", "=", $this->shop["id"]];
        $out_trade_no = input("param.out_trade_no", "", "trim");
        if ($out_trade_no) {
            $where[] = [
                "a.out_trade_no",
                "=",
                $out_trade_no
            ];
        }

        $config = [
            "query" => request()->param(),
            "list_rows" => 20
        ];
        $data = Db::table(self::TABLE)
            ->alias("a")
            ->field("a.*,b.nickname,c.shop_name,d.name printer_name")
            ->join("do_mini_user b", "a.uid=b.id", "left")
            ->join("do_shop c", "a.shop_id=c.id", "left")
            ->join("do_printer d", "a.printer_id=d.id", "left")
            ->orderRaw("field(a.out_refund_status,4,5,1) desc")
            ->order('id')
            ->where("a.out_refund_status", "<>", "0")
            ->where($where)
            ->paginate($config);

        return view(
            "index", [
            "lists" => $data,
            "pages" => $data->render()
        ]);
    }

    public function cx_dy($id, $task_id)
    {
        $data = CartModel::with(['order' => function ($query) {
            $query->with('printer');
        }])->findOrEmpty($id);
        $printer = $data['order']['printer'];
        $lianKe = new LianKePrinter($printer['device_id'], $printer['device_key']);
        $res = $lianKe->getJobStatus(1, $task_id);
        if (!empty($res['code']) && $res['code'] == 200) {
            //打印成功,更新文件状态
            $cart = CartModel::find($id);
            $task_state = $res['data']['task_state'];
            if ($task_state == 'SUCCESS') {
                $task_state = $res['data']['task_result']['code'] == 200 ? 'SUCCESS' : 'FAILURE';
            }
            $cart->save(['print_status' => getPrintMsgToStatus($task_state)]);
        }
        $return = [
            "code" => 0,
            "data" => $res['data'] ?? [],
        ];
        return json($return);
    }


    public function dy($id)
    {

        $data = CartModel::with(['order' => function ($query) {
            $query->with('printer');
        }])->findOrEmpty($id);
        if ($data->isEmpty()) {
            $return = [
                "code" => -1,
                "msg" => "无文件可打印"
            ];
        } else {
            $data = $data->toArray();
            $printer = $data['order']['printer'];
            $lianKe = new LianKePrinter($printer['device_id'], $printer['device_key']);
            $params = get_dy_params($data);
            $file = $data['file'];
            Log::write("[dy]" . var_export($params, true), "debug");
            $res = $lianKe->addJob($printer['data']['printer_info']['drivce_name'], $file, $params, $id);
            $return = [
                "code" => 0,
                "data" => [
                    "task_id" => $res['data']['task_id'] ?? "",
                ]
            ];
        }

        return $return;

    }

    public function detail()
    {
        $type = input("type");

        $id = input("param.id", 0, "intval");
        $dy_data['code'] = 0;
        if ($type == 1) {
            $pid = input("pid");
            $Web_class = $this;
            $dy_fs = $Web_class->dy($pid);
            if ($dy_fs['data']['task_id'] ?? false) {
                $dy_data['code'] = 1;
                $dy_data['task_id'] = $dy_fs['data']['task_id'];
                $dy_data['pid'] = $pid;
                $return = ['code' => 0, 'msg' => '操作成功', 'url' => (string)url('detail', ['id' => $id])];
                return json($return);
            }
        } elseif ($type == 2) {
            return $this->toYesRefund($id);
        } elseif ($type == 3) {
            return $this->toNoRefund($id);
        }
        //订单信息
        $order = Db::table(self::TABLE)
            ->where(["id" => $id])
            ->find();
        //打印的文件
        $printer_list = Db::table("do_cart")
            ->where(["order_id" => $id])
            ->select()
            ->toArray();
        //店铺信息
        $shop = Db::table("do_shop")
            ->where(["id" => $order["shop_id"]])
            ->find();
        //打印机信息
        $printer = Db::table("do_printer")
            ->where(["id" => $order["printer_id"]])
            ->find();
        $photo = Db::table("do_electronic_photo")
            ->where(['order_id' => $id])
            ->select()
            ->toArray();
        $vars = [
            "order" => $order,
            "printer_list" => $printer_list,
            "shop" => $shop,
            "printer" => $printer,
            'sddy' => $dy_data,
            'photo' => $photo
        ];

        return view("", $vars);
    }

    /**
     * @param string $order_type
     *                           EP:电子照订单
     *                           PR：printer 打印订单
     *                           TP：退款订单
     *  WD
     *
     * @throws Exception
     */

    private function makeOutTradeNo($order_type = '', $uid = ''): string
    {
        return strtoupper($order_type) . date('YmdHis') . str_pad((string)$uid, 5, '0') . random_int(
                11111,
                99999
            );
    }

    private function toYesRefund($id, $url = 'detail')
    {
        $payment = wechat(false);
        $db_order = Db::table('do_order')
            ->where('id', $id)
            ->find();
        $out_refund_no = empty($db_order['out_refund_no']) ? $this->makeOutTradeNo('TP', $db_order['uid']) : $db_order['out_refund_no'];
        $order = [
            'notify_url' => (string)url('api/notify/refund', [], null, true),
        ];

        $result = $payment->refund->byOutTradeNumber($db_order['out_trade_no'], $out_refund_no, (int)$db_order['total_fee'], (int)$db_order['out_refund_fee'], $order);
        $update['out_refund_status'] = 5;
        $update['out_refund_rejecttime'] = time();
        $update['out_refund_no'] = $out_refund_no;
        if ($result['result_code'] == 'SUCCESS') {
            $update['out_refund_status'] = 3;
        } elseif ($result['result_code'] == 'FAIL') {
            $update['out_refund_status'] = 4;
            $update['out_refund_errmsg'] = $result['err_code_des'];
        }
        $data = Db::table("do_order")
            ->where("id", $id)
            ->where("out_refund_status", 1)
            ->update($update);
        if ($data == 1) {
            $return = ['code' => 0, 'msg' => '操作成功', 'url' => (string)url($url, ['id' => $id])];
        } else {
            $return = ['code' => 1, 'msg' => '操作失败', 'url' => (string)url($url, ['id' => $id])];
        }
        return json($return);
    }

    private function toNoRefund($id, $out_refund_status, $url = 'detail', $type = false)
    {
        $data = Db::table("do_order")
            ->where("id", $id)
            ->where('out_refund_status', 'in', '1,4')
            ->update(["out_refund_status" => $out_refund_status, "out_refund_rejecttime" => time()]);
        if ($data == 1) {
            $return = ['code' => 0, 'msg' => $type ? "已过24小时,自动驳回!" : '操作成功', 'url' => (string)url($url, ['id' => $id])];
        } else {
            $return = ['code' => 1, 'msg' => '操作失败', 'url' => (string)url($url, ['id' => $id])];
        }
        return json($return);
    }
}
