<?php
declare (strict_types=1);

namespace app\shop\controller;

use think\facade\Db;
use think\facade\View;

class Shop extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        if (request()->isPost()) {

            $data = input("post.");
            Db::table("do_shop")->where(["id" => $data["id"]])->update($data);
            $return = [
                "code" => 0,
                "msg" => "操作成功"
            ];
            $shop = Db::table("do_shop")->find($data["id"]);
            session("shop", $shop);
            return json($return);
        } else {


            View::assign($this->shop);

            return view();
        }
    }
}
