<?php
declare (strict_types=1);

namespace app\proxy\controller;

use think\facade\Db;

class Account extends Common
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {

        if (request()->isPost()) {
            $post = input("post.", "", "trim");
            foreach ($post as $k => $v) {
                if (empty($v)) unset($post[$k]);
                if ($k == "BankCard") unset($post[$k]);
            }
            if ($post) {
                Db::table("do_proxy")
                    ->where(["id" => $this->proxy["id"]])
                    ->update($post);
                $return = [
                    "code" => 0,
                    "msg" => "修改成功",
                    "url" => (string)url("index")
                ];
            } else {
                $return = [
                    "code" => 1,
                    "msg" => "修改失败,密码不能为空",
                    "url" => (string)url("index")
                ];

            }
            return json($return);
        } else {
            $data = Db::table("do_proxy")->alias("a")->fieldRaw("a.*,CONCAT(LEFT ( a.BankCard, 5 ),LPAD ( RIGHT ( a.BankCard, 5 ), length( a.BankCard )- 5, \"*\" )) BankCard")->where(["id" => $this->proxy["id"]])->find();
            return view("", $data);
        }
    }
}
