<?php
declare (strict_types=1);

namespace app\proxy\controller;

use EasyWeChat\Factory;
use think\facade\Db;
use think\facade\Filesystem;

class System extends Common
{

    public const TableName = "do_system";

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {


        if (request()->isPost()) {

            $post = input("post.");
            $type = $post["type"];
            if (request()->file("img")) {
                $file = request()->file("img");
                $savename = Filesystem::putFile("mp", $file);
                $post["img"] = $savename;
            }
            unset($post["type"]);
            $insert = [
                "type" => $type,
                "data" => json_encode($post),
                "proxy_id" => $this->proxy["id"]
            ];
            $where = [
                "type" => $type,
                "proxy_id" => $this->proxy["id"]
            ];
            $data = Db::table(self::TableName)
                ->where($where)
                ->findOrEmpty();
            if (empty($data)) {
                Db::table(self::TableName)
                    ->insert($insert);
            } else {
                Db::table(self::TableName)
                    ->where(["type" => $type])
                    ->update($insert);
            }

            return json(["msg" => "操作成功"]);

        } else {

            $data = Db::table(self::TableName)
                ->where(["shop_id" => $this->proxy["id"]])
                ->select()
                ->toArray();
            $vars = [];
            if (!empty($data)) {
                foreach ($data as $k => $v) {
                    $vars[$v["type"]] = json_decode($v["data"], true);
                }
            }

            return view('', $vars);
        }
    }

}
